services:
  - type: web
    name: family-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YANDEX_TOKEN
        sync: false
      - key: PUBLIC_KEY
        sync: false
      - key: RENDER_URL
        value: https://family-finance-bot.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
